### ISSUE TITLE
authors tagging

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/ModelCriteriaProject#4]
Our format allows only two specific author tagging statements, "These authors contributed equally" and "These authors jointly supervised this work", with one of each tag allowed.

**Comment by shiranab** [comment]
change the acknowledgements too, and the emails in the end

**Comment by DanaAzouri** [comment]
Changed author tagging (title page), 
and updated Authorship section with more details of each contribution.

**Comment by shiranab** [comment]
removed the section "correspondance and materials" (as they wrote to do in the pdf comments)
